### PR TITLE
feat: Use currency specified by display currency from backend

### LINKED ISSUE #33: Use correct currency symbol in Order List & Order Detail Screen
**Is your feature request related to a problem? Please describe.**
[`OrderDetailScreen`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/screens/OrderDetailScreen/index.js) & [`OrdersScreen`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/screens/OrdersScreen/index.js) should use currency symbol that you get using `order_currency_code` which is being fetched using API. Not the current default selected in App (id App supports multiple currency)

**Describe the solution you'd like**
Make sure that currency symbol shown and the price is the same which were used at the time of placing the order.

**Additional context**
This will be make more sense after #58 is implemented

### LINKED ISSUE #82: Getting Currency Symbol Error
Hi,
My website belongs to kuwait . And i am using Kuwati Dinnar in currency . Now as i can for USD its working fine . But when i changed currency KWD. It is giving error . When i tried to installed it . That time it was also showing currency symbol warning .

### PR DESCRIPTION
**Pull request by alexakasanjeev**
**What does this implement/fix? Explain your changes.**
Magento 2 support base currency and display currency, if base and display currency are different, update the prices and currency symbol to reflect display currency. also if multiple currency support is there, let user to change display currency locally in APP

**Does this close any currently open issues?**
close #82, close #33

**Any other comments?**

**Where has this been tested?**
---------------------------
 - Magento Version: [2.1.0]
 - Device: [Android Emulator Nexus Nexus ONE]
 - OS: [9.0 (Pie) - API 28]

### CODE REVIEW

**Comment by piyush9015** [comment]
but i have only one currency still giving error . It is showing null . I already post the question . But did not get any solution since 15 days.

**Comment by piyush9015** [comment]
Screenshot_53
Screenshot_54

**Comment by alexakasanjeev** [comment]
Hi @piyush9015 Did you use latest code, please fork the latest build from `develop` branch, and test out.

**Comment by piyush9015** [comment]
pleaes change the token all are same

arx6gs404wmcj5iylic981gkxvbm7vef

**Comment by alexakasanjeev** [comment]
Whihc token you are asking to change?

**Pull request merged**
